jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8080
   servlet:
      context-path: /
      session:
         timeout: 21600s

spring:
   profiles:
      active: ''
   flyway:
        enabled: false
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://alquiler-autos-de-lujo.mysql.database.azure.com:3306/adn_ceiba?useSSL=true&requireSSL=false&serverTimezone=America/Bogota
      username: admont28@alquiler-autos-de-lujo
      password: CSH*1094937274
      hikari:
         poolName: pool
logging:
    level:
        org:
            springframework:
                jdbc:
                    core: TRACE
            
                