jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8080
   servlet:
      context-path: /
      session:
         timeout: 21600s

spring:
   application:
      name: Alquiler Autos de Lujo
   jms:
      servicebus:
        connection-string: ${AZURE_SERVICE_BUS_CONNECTION_STRING}
        idle-timeout: ${AZURE_SERVICE_BUS_IDLE_TIMEOUT}
        queue-name: ${AZURE_SERVICE_BUS_DEFAULT_QUEUE_NAME}
   azure:
      blob:
        store:
          connectionString: ${AZURE_BLOB_STORAGE_CONNECTION_STRING}
          containerName: ${AZURE_BLOG_STORAGE_CONNECTION_NAME}
   profiles:
      active: ''
   flyway:
      enabled: ${FLYWAY_ENABLED}
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: ${MYSQLCONNSTR_ADN_CEIBA}
      username: ${DATABASE_USERNAME:root}
      password: ${DATABASE_PASSWORD:root}
      hikari:
        poolName: pool
logging:
    level:
        org:
            springframework:
                jdbc:
                    core: TRACE
