jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8080
   servlet:
      context-path: /
      session:
         timeout: 21600s

spring:
   profiles:
      active: ''
   flyway:
        enabled: false
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: ${MYSQLCONNSTR_ADN_CEIBA}
      username: ${DATABASE_USERNAME:root}
      password: ${DATABASE_PASSWORD:root}
      hikari:
         poolName: pool
logging:
    level:
        org:
            springframework:
                jdbc:
                    core: TRACE
            
                