server:
   port: 8080
   servlet:
      context-path: /
      session:
         timeout: 21600s
spring:
   application:
      name: Alquiler Autos de Lujo
   flyway:
        enabled: true
   datasource:
      driver-class-name: org.h2.Driver
      jdbcUrl: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
      username: sa
      password:
      hikari:
         poolName: pool
logging:
    level:
        org:
            springframework:
                jdbc:
                    core: INFO
                