jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8080
   servlet:
      context-path: /
      session:
         timeout: 21600s

spring:
   azure:
      blob:
        store:
          connectionString: ${AZURE_BLOB_STORAGE_CONNECTION_STRING}
          containerName: ${AZURE_BLOG_STORAGE_CONNECTION_NAME}
   profiles:
      active: ''
   flyway:
      enabled: true
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/adn_ceiba?serverTimezone=America/Bogota
      username: root
      password: root
      hikari:
        poolName: pool
logging:
    level:
        org:
            springframework:
                jdbc:
                    core: TRACE
